name = "SplinePlacer"
prefix = "splineplacer"
mainprefix = "z"

[hemtt.launch.default]
parameters = [
    "-name=Shadow",
    #"-exThreads=7",
    #"-enableHT",
    "-malloc=jemalloc_bi_x64",
    #"-hugePages",
    "-world=empty",
    '"C:\Users\Claude\Documents\GitHub\arma3-splineplacer\addons\main\mpmissions\LineBuilder.VR\mission.sqm"',
]

[hemtt.release]
archive = false # Default: true

[version]
major = 1
minor = 0
patch = 3

[files]
exclude = ["*.blend"]

[lints.sqf]
"s02ic" = "suppress"
